apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: twipeater
  name: twipeater
spec:
  serviceName: twipeater
  replicas: 1
  selector:
    matchLabels:
      app: twipeater
  template:
    metadata:
      labels:
        app: twipeater
    spec:
      containers:
      - name: twipeater
        image: twipeater
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            
---
apiVersion: v1
kind: Service
metadata:
  name: twipeater
  annotations:
    k8sdns: twipeater
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: twipeater
  type: ClusterIP